
version: '3.8'
services:
  stock_price_checker_db:
    image: postgres:15.5-alpine3.19
    restart: always
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=stock_price_checker_dev_user
      - POSTGRES_PASSWORD=Fd0kjmjYjzAUXx3C
      - POSTGRES_DB=stock_price_checker_development
    ports:
      - 5600:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 5s
      timeout: 3s
      retries: 5
    volumes: 
      - stock_price_checker_db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/create_tables.sql
  stock_price_checker_cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - 6500:6379
    command: redis-server --save 20 1 --loglevel warning
    volumes: 
      - stock_price_checker_cache:/data
  stock_price_checker_api:
    container_name: stock_price_checker_api-service
    build:
      context: ./
      dockerfile: Dockerfile.dev
    image: stock-price-checker-api
    depends_on:
      stock_price_checker_db:
        condition: service_healthy
      stock_price_checker_cache:
        condition: service_started
    ports:
      - 8200:8200
    environment:
      NODE_ENV: development
      COMPOSE: true
      PORT: 8200
      DATABASE_HOST: stock_price_checker_db
      DATABASE_PORT: 5432
      DATABASE_USERNAME: stock_price_checker_dev_user
      DATABASE_PASSWORD: Fd0kjmjYjzAUXx3C
      DATABASE_DATABASE: stock_price_checker_development
      REDIS_HOST: stock_price_checker_cache
      REDIS_PORT: 6379
    command: npm run start:dev
    links:
      - stock_price_checker_db
      - stock_price_checker_cache
    volumes:
      - type: bind
        source: ./src
        target: /usr/src/app/src
volumes:
  stock_price_checker_db:
    driver: local
  stock_price_checker_cache:
    driver: local